### ISSUE TITLE
gem not working when trying to launch app

### ISSUE THREAD

**Issue by aronlmin** [KoanHealth/mongoid-encrypted-fields#28]
## Errors when launching app
```bash
aronlilland:backbone_cac_grape$ bundle exec rackup -p 3030
/Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler/runtime.rb:85:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'mongoid-encrypted-fields'. (Bundler::GemRequireError)
Gem Load Error is: "6.2.0" is not a class/module
Backtrace for gem load error is:
/Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/mongoid-encrypted-fields-1.3.4/lib/mongoid-encrypted-fields.rb:32:in `<top (required)>'
/Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler/runtime.rb:82:in `require'
/Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
/Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler/runtime.rb:77:in `each'
/Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler/runtime.rb:77:in `block in require'
/Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler/runtime.rb:66:in `each'
/Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler/runtime.rb:66:in `require'
/Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler.rb:108:in `require'
/Users/aronlilland/Documents/ruby/backbone_cac_grape/config.ru:5:in `block in <main>'
/Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/rack-1.6.8/lib/rack/builder.rb:55:in `instance_eval'
/Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/rack-1.6.8/lib/rack/builder.rb:55:in `initialize'
/Users/aronlilland/Documents/ruby/backbone_cac_grape/config.ru:in `new'
/Users/aronlilland/Documents/ruby/backbone_cac_grape/config.ru:in `<main>'
/Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/rack-1.6.8/lib/rack/builder.rb:49:in `eval'
/Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/rack-1.6.8/lib/rack/builder.rb:49:in `new_from_string'
/Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/rack-1.6.8/lib/rack/builder.rb:40:in `parse_file'
/Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/rack-1.6.8/lib/rack/server.rb:300:in `build_app_and_options_from_config'
/Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/rack-1.6.8/lib/rack/server.rb:209:in `app'
/Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/rack-1.6.8/lib/rack/server.rb:337:in `wrapped_app'
/Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/rack-1.6.8/lib/rack/server.rb:273:in `start'
/Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/rack-1.6.8/lib/rack/server.rb:148:in `start'
/Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/rack-1.6.8/bin/rackup:4:in `<top (required)>'
/Users/aronlilland/.rvm/gems/ruby-2.3.3/bin/rackup:22:in `load'
/Users/aronlilland/.rvm/gems/ruby-2.3.3/bin/rackup:22:in `<main>'
/Users/aronlilland/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
/Users/aronlilland/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
Bundler Error Backtrace:
	from /Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
	from /Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler/runtime.rb:77:in `each'
	from /Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler/runtime.rb:77:in `block in require'
	from /Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler/runtime.rb:66:in `each'
	from /Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler/runtime.rb:66:in `require'
	from /Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler.rb:108:in `require'
	from /Users/aronlilland/Documents/ruby/backbone_cac_grape/config.ru:5:in `block in <main>'
	from /Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/rack-1.6.8/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/rack-1.6.8/lib/rack/builder.rb:55:in `initialize'
	from /Users/aronlilland/Documents/ruby/backbone_cac_grape/config.ru:in `new'
	from /Users/aronlilland/Documents/ruby/backbone_cac_grape/config.ru:in `<main>'
	from /Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/rack-1.6.8/lib/rack/builder.rb:49:in `eval'
	from /Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/rack-1.6.8/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/rack-1.6.8/lib/rack/builder.rb:40:in `parse_file'
	from /Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/rack-1.6.8/lib/rack/server.rb:300:in `build_app_and_options_from_config'
	from /Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/rack-1.6.8/lib/rack/server.rb:209:in `app'
	from /Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/rack-1.6.8/lib/rack/server.rb:337:in `wrapped_app'
	from /Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/rack-1.6.8/lib/rack/server.rb:273:in `start'
	from /Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/rack-1.6.8/lib/rack/server.rb:148:in `start'
	from /Users/aronlilland/.rvm/gems/ruby-2.3.3/gems/rack-1.6.8/bin/rackup:4:in `<top (required)>'
	from /Users/aronlilland/.rvm/gems/ruby-2.3.3/bin/rackup:22:in `load'
	from /Users/aronlilland/.rvm/gems/ruby-2.3.3/bin/rackup:22:in `<main>'
	from /Users/aronlilland/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/aronlilland/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
aronlilland:backbone_cac_grape$ 
```
## Gemfile
```ruby
source 'http://rubygems.org'

ruby '2.3.3'

gem 'grape'
gem 'grape-entity'

gem 'dotenv'

gem 'rack'
gem 'rack-contrib'
gem 'rack-cors'
gem 'puma'

gem 'sinatra'

gem 'mongoid'
gem "mongoid-encrypted-fields"
gem "sanitize"

gem 'symmetric-encryption'
gem "gibberish"
gem 'postmark'
```

## config.ru
```ruby
## Dependencies
require 'csv'
require 'bundler'

Bundler.require :default
Dotenv.load

## Main application files
require './app.rb'

## CORS
require 'rack/cors'
use Rack::Cors do
	allow do
		origins '*'
		resource '*', headers: :any, methods: [:get, :post, :options, :put, :delete]
	end
end

## Run the Grape API
run Rack::Cascade.new [BACKBONE::API]
```

**Comment by jerryclinesmith** [comment]
Unfortunately, the gem failed in the code that validates your version of Mongoid.  I've made some updates and pushed a new gem, please grab the latest and let me know if it works.

**Comment by aronlmin** [comment]
@jerryclinesmith fixed 👍 thank you!
